services:
  db:
    image: postgres:16
    container_name: ward_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ward_perfumes
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Opcional: interfaz web para administrar la BD (http://localhost:8080)
  adminer:
    image: adminer
    container_name: ward_adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pg_data:
